server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springTable?characterEncoding=UTF-8&useSSL=false
    username: admin
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update